version: '3.9'

services:
  db:
    image: postgres:15
    container_name: eir_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imei_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount SQL files for easy access
      - ./backend/schema_postgres.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/test_data.sql:/docker-entrypoint-initdb.d/02-test-data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./backend
    container_name: eir_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/schema_postgres.sql:/app/schema_postgres.sql
      - ./backend/test_data.sql:/app/test_data.sql
      - ./scripts:/app/scripts
      - ./config:/app/config
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/imei_db

volumes:
  postgres_data:
