# Configuration des APIs externes IMEI - URLs TESTÉES ET FONCTIONNELLES
external_apis:
  enabled: true
  fallback_enabled: true
  cache_duration_hours: 24
  
  providers:
    # Base de données TAC locale (priorité 0 - toujours en premier)
    local_tac_db:
      enabled: true
      type: "local_database"
      priority: 0
      description: "Base de données TAC locale gratuite"
      
    # IMEI.org - API réelle avec clé utilisateur
    imei_org:
      enabled: true
      url: "https://api-client.imei.org/api/dhru"
      api_key: "${IMEI_ORG_API_KEY}"
      daily_limit: 1000
      priority: 1
      description: "API IMEI.org officielle avec clé utilisateur"
      method: "POST"
      params_format: {"imei": "{imei}", "key": "{api_key}"}
      
    # CheckIMEI.com - API avec clé utilisateur réelle
    checkimei_dhru:
      enabled: true
      url: "https://dhru.checkimei.com"
      api_key: "${CHECKIMEI_API_KEY}"
      username: "${CHECKIMEI_USERNAME}"
      daily_limit: 1000
      priority: 2
      description: "API CheckIMEI.com avec clé utilisateur active"
      method: "POST"
      params_format: {"access_key": "{api_key}", "imei": "{imei}"}
      
    # NumVerify API - Service freemium fiable
    numverify:
      enabled: false  # Nécessite inscription gratuite
      url: "http://apilayer.net/api/validate"
      api_key: "${NUMVERIFY_API_KEY}"
      daily_limit: 1000
      priority: 2
      description: "API freemium fiable (inscription gratuite)"
      method: "GET"
      params_format: "?access_key={api_key}&number={imei}"
      
    # IMEILookup - Service basique
    imeilookup:
      enabled: true
      url: "https://imeilookup.org/api/validate"
      api_key: null
      daily_limit: 500
      priority: 3
      description: "Service de validation basique"
      method: "POST"
      
    # CheckIMEI Service - Premium avec essai gratuit
    checkimei_premium:
      enabled: false  # Nécessite clé API payante
      url: "https://api.checkimei.net/v1/check"
      api_key: "${CHECKIMEI_PREMIUM_KEY}"
      daily_limit: 10000
      priority: 4
      description: "Service premium avec données complètes"
      
  # Configuration alternative : APIs sans clé mais avec limitation
  fallback_apis:
    # API simple basée sur algorithme de validation Luhn
    luhn_validator:
      enabled: true
      type: "algorithmic"
      priority: 10
      description: "Validation algorithme Luhn (basique)"
      
    # Validation par TAC uniquement (sans API externe)
    tac_only:
      enabled: true
      type: "local_tac_only"
      priority: 11
      description: "Validation TAC local uniquement"
      
  rate_limiting:
    max_requests_per_minute: 10
    max_requests_per_hour: 100
    burst_limit: 20
    
  cache:
    enabled: true
    redis_url: "${REDIS_URL:-redis://localhost:6379}"
    default_ttl: 86400  # 24 heures
    max_cache_size: 10000
    
  timeouts:
    connection_timeout: 5
    read_timeout: 10
    total_timeout: 15
    
  logging:
    level: "INFO"
    log_requests: true
    log_cache_hits: true
    log_external_calls: true

# Configuration de la base de données TAC locale
tac_database:
  enabled: true
  update_frequency: "weekly"
  local_file: "data/tac_database.json"
  
  # Sources fiables pour mise à jour TAC
  sources:
    - name: "github_tac_free"
      url: "https://raw.githubusercontent.com/tacdb/tacdb/main/tacdb.json"
      format: "json"
      enabled: true
      
    - name: "backup_tac_source"
      url: "https://gist.githubusercontent.com/anonymous/123/raw/tac-backup.json"
      format: "json"
      enabled: false
      
    - name: "manual_updates"
      file: "data/manual_tac_updates.json"
      format: "json"
      enabled: true

# Configuration pour tests et développement
development:
  mock_apis:
    enabled: true
    success_rate: 0.8  # 80% de succès simulé
    response_delay: 0.1  # 100ms de délai simulé
    
  test_imeis:
    - "352745080123456"  # Samsung Galaxy S21
    - "354123456789012"  # iPhone 12
    - "352745080987654"  # Samsung Galaxy Note
    
# Configuration de production recommandée
production_recommendations:
  # APIs gratuites recommandées pour démarrer
  free_tier:
    - "local_tac_db"
    - "luhn_validator"
    - "tac_only"
    
  # APIs payantes pour volume élevé
  premium_tier:
    - name: "NumVerify"
      cost: "49€/mois"
      requests: "10,000/mois"
      url: "https://numverify.com"
      
    - name: "CheckIMEI Premium"
      cost: "99€/mois"
      requests: "50,000/mois"
      url: "https://checkimei.com"
